version: '3'

services:

    jorani:
      container_name: rps_jorani
      build:
        context: .
        dockerfile: Dockerfile
      image: jorani
      restart: always
      ports:
       - "80:80"
      links:
       - mysql

    mysql:
      image: mysql:5.5
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=lms

      volumes:
        - db-data:/var/lib/mysql/data
        - ./lms.sql:/docker-entrypoint-initdb.d/lms.sql

volumes:
  db-data: