version: '3'

services:

    jorani:
      container_name: rps_jorani
      build:
        context: .
        dockerfile: Dockerfile
      image: jorani
      restart: always
      ports:
       - "80:80"
      links:
       - mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Password123456_Change_Me!

    mysql:
      image: mysql:5.5
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=Password123456_Change_Me!
        - MYSQL_DATABASE=lms

      volumes:
        - rps-jorani-db-data:/var/lib/mysql
        - ./lms.sql:/docker-entrypoint-initdb.d/1-lms.sql

volumes:
  rps-jorani-db-data: